
# backtraces_path = "/path/to/neovide_backtraces.log" # see below for the default platform specific location
fork = false
frame = "none"
idle = true
maximized = true
mouse-cursor-icon = "arrow"
# neovim-bin = "/usr/bin/nvim" # in reality found dynamically on $PATH if unset
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
title-hidden = true
vsync = true
wsl = false

[font]
normal = "BlexMono Nerd Font Mono"
# normal = "Inconsolata Nerd Font Mono"
# normal = "0xProto Nerd Font"
# normal = "CaskaydiaCove Nerd Font Mono"
# normal = "DMMono Nerd Font"

size = 13.0
# linespace = 2

[box-drawing]
# "font-glyph", "native" or "selected-native"
mode = "font-glyph"

[box-drawing.sizes]
default = [2, 4] # Thin and thick vaues respectively, for all sizes
