
# ===== Geral =====
# Pede confirmação pra fechar? (false = não pergunta)
confirm-before-quit = false

[general]
working-directory = "$HOME"

# ===== Cursor =====
[cursor]
shape = "block"
blinking = false
hide-cursor-when-typing = false

[fonts]
size = 16
features = []
use-drawable-chars = true
symbol-map = []
additional-dirs = []
hinting = true            # antes estava como fonts.hinting; mantém aqui

disable-warnings-not-found = false

[fonts.regular]
# family = "Hack Nerd Font"
# family = "BlexMono Nerd Font"
# family = "GeistMono Nerd Font"
# family = "Terminess Nerd Font Mono"
family = "JetBrainsMono Nerd Font"
style = "Normal"
width = "Normal"
weight = 400

[fonts.bold]
family = "JetBrainsMono Nerd Font"
style = "Normal"
width = "Normal"
weight = 800

[fonts.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"
width = "Normal"
weight = 400

[fonts.bold-italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"
width = "Normal"
weight = 800

[navigation]
use-split = true

[window]

mode = "Maximized"
opacity = 0.9
blur = true
decorations = "disabled" # outras: "Enabled" | "Disabled" | "Buttonless"
# draw-bold-text-with-light-colors = false
# [window.background-image]
# path = "~/dotfiles/.config/wezterm/bg-blurred.png"
