SELECT
    RESULT.CLIENTE,
    SUM(RESULT.GARANTIA_S) AS GARANTIA_S,
    SUM(RESULT.GARANTIA_N) AS GARANTIA_N,
    SUM(RESULT.ORIGEM_INOVA) AS ORIGEM_INOVA,
    SUM(RESULT.ORIGEM_CLIENTE) AS ORIGEM_CLIENTE,
    SUM(RESULT.QTDE_VENDAS) AS QTDE_VENDAS,
    CASE
        WHEN SUM(RESULT.QTDE_VENDAS) = 0 THEN 0
        ELSE ROUND((SUM(RESULT.GARANTIA_S) + SUM(RESULT.GARANTIA_N)) / SUM(RESULT.QTDE_VENDAS) * 100, 2)
    END AS PORCENTAGEM_GARANTIA
FROM (
    SELECT
        CLIENTES.CLIENTE,
        NVL(DADOS_GARANTIA.ITEM_GARANTIA_S, 0) AS GARANTIA_S,
        NVL(DADOS_GARANTIA.ITEM_GARANTIA_N, 0) AS GARANTIA_N,
        NVL(DADOS_GARANTIA.ITEM_ORIGEM_INOVA_7, 0) AS ORIGEM_INOVA,
        NVL(DADOS_GARANTIA.ITEM_ORIGEM_CLIENTE_1, 0) AS ORIGEM_CLIENTE,
        NVL(DADOS_VENDAS.QTDE_VENDAS, 0) AS QTDE_VENDAS
    FROM (
        SELECT DISTINCT CLIENTE, COD_CLIENTE
        FROM (
            SELECT '124 - PROGAS / 175 - BRAESI' AS CLIENTE, 124 AS COD_CLIENTE FROM DUAL
            UNION ALL
            SELECT '124 - PROGAS / 175 - BRAESI', 175 FROM DUAL
            UNION ALL
            SELECT '2833 - PROGEU ACESSORIOS / 3368 - IGUI', 2833 FROM DUAL
            UNION ALL
            SELECT '2833 - PROGEU ACESSORIOS / 3368 - IGUI', 3368 FROM DUAL
            UNION ALL
            SELECT
                CAST(PPA001_PESSOA || ' - ' || PPA001_NOME AS VARCHAR2(100)) AS CLIENTE,
                CAST(PPA001_PESSOA AS NUMBER) AS COD_CLIENTE
            FROM PPTBA001
            WHERE PPA001_PESSOA IN (
                226, 235, 240, 631, 42, 244, 4337, 377,
                12, 6836, 3755, 99, 371, 323
            )
        )
        WHERE (:CLIENTE IS NULL OR :CLIENTE = 0 OR COD_CLIENTE = :CLIENTE)
    ) CLIENTES
    LEFT JOIN (
        SELECT
            CLIENTES_TEMP.CLIENTE,
            COUNT(CASE WHEN O10.ORC010_GARANTIA = 'S' THEN 1 END) AS ITEM_GARANTIA_S,
            COUNT(CASE WHEN O10.ORC010_GARANTIA = 'N' THEN 1 END) AS ITEM_GARANTIA_N,
            COUNT(CASE WHEN O10.ORC010_ORIGEMPROBLEMA = 7 THEN 1 END) AS ITEM_ORIGEM_INOVA_7,
            COUNT(CASE WHEN O10.ORC010_ORIGEMPROBLEMA = 1 THEN 1 END) AS ITEM_ORIGEM_CLIENTE_1
        FROM (
            SELECT DISTINCT CLIENTE, COD_CLIENTE
            FROM (
                SELECT '124 - PROGAS / 175 - BRAESI' AS CLIENTE, 124 AS COD_CLIENTE FROM DUAL
                UNION ALL
                SELECT '124 - PROGAS / 175 - BRAESI', 175 FROM DUAL
                UNION ALL
                SELECT '2833 - PROGEU ACESSORIOS / 3368 - IGUI', 2833 FROM DUAL
                UNION ALL
                SELECT '2833 - PROGEU ACESSORIOS / 3368 - IGUI', 3368 FROM DUAL
                UNION ALL
                SELECT
                    CAST(PPA001_PESSOA || ' - ' || PPA001_NOME AS VARCHAR2(100)) AS CLIENTE,
                    CAST(PPA001_PESSOA AS NUMBER) AS COD_CLIENTE
                FROM PPTBA001
                WHERE PPA001_PESSOA IN (
                    226, 235, 240, 631, 42, 244, 4337, 377,
                    12, 6836, 3755, 99, 371, 323
                )
            )
            WHERE (:CLIENTE IS NULL OR :CLIENTE = 0 OR COD_CLIENTE = :CLIENTE)
        ) CLIENTES_TEMP
        LEFT JOIN ORTBC001 O01
            ON (
                (CLIENTES_TEMP.COD_CLIENTE IS NOT NULL AND CLIENTES_TEMP.COD_CLIENTE = O01.ORC001_PESSOA)
                OR (CLIENTES_TEMP.CLIENTE = '124 - PROGAS / 175 - BRAESI' AND O01.ORC001_PESSOA IN (124, 175))
                OR (CLIENTES_TEMP.CLIENTE = '2833 - PROGEU ACESSORIOS / 3368 - IGUI' AND O01.ORC001_PESSOA IN (2833, 3368))
            )
            AND O01.ORC001_DTFINALIZADO BETWEEN :DATAINI AND :DATAFIM
        LEFT JOIN ORTBC010 O10
            ON O01.ORC001_GRUPO = O10.ORC010_GRUPO
            AND O01.ORC001_EMPRESA = O10.ORC010_EMPRESA
            AND O01.ORC001_FILIAL = O10.ORC010_FILIAL
            AND O01.ORC001_TIPODOC = O10.ORC010_TIPODOC
            AND O01.ORC001_ORDEM = O10.ORC010_ORDEM
            AND O01.ORC001_ID = O10.ORC010_ORC001_ID
        WHERE
            (:GARANTIA IS NULL OR :GARANTIA = '0' OR O10.ORC010_GARANTIA = :GARANTIA)
            AND (:ORIGEM IS NULL OR :ORIGEM = 0 OR O10.ORC010_ORIGEMPROBLEMA = :ORIGEM)
        GROUP BY CLIENTES_TEMP.CLIENTE
    ) DADOS_GARANTIA ON CLIENTES.CLIENTE = DADOS_GARANTIA.CLIENTE
    LEFT JOIN (
        SELECT
            CLIENTES_TEMP.CLIENTE,
            NVL(SUM(NSB001_QTDE), 0) AS QTDE_VENDAS
        FROM (
            SELECT DISTINCT CLIENTE, COD_CLIENTE
            FROM (
                SELECT '124 - PROGAS / 175 - BRAESI' AS CLIENTE, 124 AS COD_CLIENTE FROM DUAL
                UNION ALL
                SELECT '124 - PROGAS / 175 - BRAESI', 175 FROM DUAL
                UNION ALL
                SELECT '2833 - PROGEU ACESSORIOS / 3368 - IGUI', 2833 FROM DUAL
                UNION ALL
                SELECT '2833 - PROGEU ACESSORIOS / 3368 - IGUI', 3368 FROM DUAL
                UNION ALL
                SELECT
                    CAST(PPA001_PESSOA || ' - ' || PPA001_NOME AS VARCHAR2(100)) AS CLIENTE,
                    CAST(PPA001_PESSOA AS NUMBER) AS COD_CLIENTE
                FROM PPTBA001
                WHERE PPA001_PESSOA IN (
                    226, 235, 240, 631, 42, 244, 4337, 377,
                    12, 6836, 3755, 99, 371, 323
                )
            )
            WHERE (:CLIENTE IS NULL OR :CLIENTE = 0 OR COD_CLIENTE = :CLIENTE)
        ) CLIENTES_TEMP
        LEFT JOIN NSTBA001
            ON (
                (CLIENTES_TEMP.COD_CLIENTE IS NOT NULL AND CLIENTES_TEMP.COD_CLIENTE = NSA001_CLIENTE)
                OR (CLIENTES_TEMP.CLIENTE = '124 - PROGAS / 175 - BRAESI' AND NSA001_CLIENTE IN (124, 175))
                OR (CLIENTES_TEMP.CLIENTE = '2833 - PROGEU ACESSORIOS / 3368 - IGUI' AND NSA001_CLIENTE IN (2833, 3368))
            )
            AND NSA001_DTEMISSAO BETWEEN :DATAINI AND :DATAFIM
        LEFT JOIN NSTBB001 NSB001
            ON NSA001_GRUPO = NSB001.NSB001_GRUPO
            AND NSA001_EMPRESA = NSB001.NSB001_EMPRESA
            AND NSA001_FILIAL = NSB001.NSB001_FILIAL
            AND NSA001_TIPODOC = NSB001.NSB001_TIPODOC
            AND NSA001_NOTA = NSB001.NSB001_NOTA
            AND NSA001_SERIE = NSB001.NSB001_SERIE
        GROUP BY CLIENTES_TEMP.CLIENTE
    ) DADOS_VENDAS ON CLIENTES.CLIENTE = DADOS_VENDAS.CLIENTE
) RESULT
GROUP BY RESULT.CLIENTE
ORDER BY PORCENTAGEM_GARANTIA DESC