return {
	"scottmckendry/cyberdream.nvim",
	lazy = false,
	priority = 1000,
	opts = function(_, opts)
		opts.transparent = true
		opts.italic_comments = true
		opts.extensions = {
			alpha = true,
			blinkcmp = true,
			cmp = true,
			dashboard = true,
			fzflua = true,
			gitpad = true,
			gitsigns = true,
			grapple = true,
			grugfar = true,
			heirline = true,
			helpview = true,
			hop = true,
			indentblankline = true,
			kubectl = true,
			lazy = true,
			leap = true,
			markdown = true,
			markview = true,
			mini = true,
			noice = true,
			neogit = true,
			notify = true,
			rainbow_delimiters = true,
			snacks = true,
			telescope = true,
			treesitter = true,
			treesittercontext = true,
			trouble = true,
			whichkey = true,
		}
	end,
}
