[env]
TERM = "xterm-256color"

# [terminal.shell]
# program = "C:\\Program Files\\Git\\bin\\bash.exe"
# args = ["--login", "-i"]

[window]
dynamic_padding = false
decorations = "None"
opacity = 1.0
title = "Alacritty"
decorations_theme_variant = "Dark"

[window.dimensions]
columns = 120 # WezTerm: initial_cols
lines = 35    # WezTerm: initial_rows

[window.padding]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 3

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
# Barra fixa (equivalente ao SteadyBar do WezTerm)
style = { shape = "Beam", blinking = "Off" }
unfocused_hollow = true
thickness = 0.15

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[keyboard]
[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control"
action = "Copy"

# extra do wezterm: Ctrl+L limpa notificações -> aqui mapeado para limpar a tela
[[keyboard.bindings]]
key = "L"
mods = "Control"
chars = "\f"

[general]
live_config_reload = true
working_directory = "None"
